services:
  db:
    image: postgres:17
    container_name: stackschool-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: stackschool-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: infra/docker/dockerfile.api
    container_name: stackschool-api
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages/shared:/app/packages/shared
      - ./packages/db:/app/packages/db
      - api_node_modules:/app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store

    ports:
      - "4000:4000"
      - "5555:5555"
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: infra/docker/dockerfile.web
    container_name: stackschool-web
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages/shared:/app/packages/shared
      - ./packages/ui:/app/packages/ui
      - ./packages/db:/app/packages/db
      - web_node_modules:/app/node_modules
      - pnpm_store:/root/.local/share/pnpm/store
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"
    depends_on:
      - api

volumes:
  db_data:
  api_node_modules:
  web_node_modules:
  pnpm_store:
