services:
  db:
    image: postgres:17
    container_name: stackschool-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: stackschool-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: infra/docker/dockerfile.backend
    container_name: stackschool-backend
    # mount only source code for hot-reload; keep lockfile and manifests inside the image
    volumes:
      - ./packages:/app/packages
      - backend_node_modules:/app/node_modules
      # persist pnpm store across container restarts to speed up installs
      #- pnpm_store:/pnpm-store
    ports:
      - "4000:4000"
      - "5555:5555"
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://redis:6379"
      JWT_SECRET: ${JWT_SECRET}

    depends_on:
      - db
      - redis
    command: pnpm --filter @stackschool/backend run dev

  frontend:
    build:
      context: .
      dockerfile: infra/docker/dockerfile.frontend
    container_name: stackschool-frontend
    volumes:
      - ./packages:/app/packages
      - frontend_node_modules:/app/node_modules
      - pnpm_store:/pnpm-store
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
    depends_on:
      - backend

volumes:
  db_data:
    external: true
    name: stack-school-moi_db_data
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local
  pnpm_store:
